### ISSUE TITLE
Build fails to link.

### ISSUE THREAD

**Issue by markrages** [azonenberg/scopehal-cmake#13]
Following instructions in README, applying workaround from #12 .
```
[ 94%] Linking CXX executable glscopeclient
../../lib/scopehal/libscopehal.so: undefined reference to `lxi_init()'
../../lib/scopehal/libscopehal.so: undefined reference to `lxi_connect(char*, int, char*, int, lxi_protocol_t)'
../../lib/scopehal/libscopehal.so: undefined reference to `lxi_receive(int, char*, int, int)'
../../lib/scopehal/libscopehal.so: undefined reference to `lxi_send(int, char*, int, int)'
collect2: error: ld returned 1 exit status
```
These functions don't seem to be defined, only used.

```
markrages@qountdown:~/src/scopehal-cmake$ grep -r lxi_connect
lib/scopehal/SCPILxiTransport.cpp:	m_device = lxi_connect(m_hostname.c_str(), m_port, "inst0", m_timeout, VXI11);
Binary file build/lib/scopehal/libscopehal.so matches
Binary file build/lib/scopehal/CMakeFiles/scopehal.dir/SCPILxiTransport.cpp.o matches
```

**Comment by azonenberg** [comment]
Those are liblxi functions so it's related to linking of liblxi.

**Comment by markrages** [comment]
```
markrages@qountdown:~/src/scopehal-cmake/build$ apt search liblxi
Sorting... Done
Full Text Search... Done
liblxi-dev/bionic,now 1.8-1 amd64 [installed]
  LAN eXtensions for Instrumentation (LXI) software interface

liblxi1/bionic,now 1.8-1 amd64 [installed,automatic]
  LAN eXtensions for Instrumentation (LXI) software interface
```

**Comment by markrages** [comment]
```
markrages@qountdown:~$ nm -gD /usr/lib/x86_64-linux-gnu/liblxi.so | grep lxi_
0000000000001860 T lxi_connect
0000000000001a00 T lxi_disconnect
0000000000001b00 T lxi_discover
0000000000001830 T lxi_init
0000000000001ac0 T lxi_receive
0000000000001a80 T lxi_send
```

but the linker can't see it?

**Comment by azonenberg** [comment]
We've had at least one other user with this same issue, also on 18.04. The LXI code is pretty new (past week or two) and this didn't show up during initial testing on more recent systems. We're still working to identify a root cause and proper fix.

Can you try removing liblxi from the distro package and installing liblxi 1.13 or newer from https://github.com/lxi-tools/liblxi?

**Comment by markrages** [comment]
Will try rebooting like Windows 98, as suggested by https://github.com/azonenberg/scopehal/issues/115

`ldconfig` didn't help.

**Comment by markrages** [comment]
Replacing the system liblxi with git pull of liblxi works, for reasons I don't understand.

**Comment by azonenberg** [comment]
We've had numerous issues with 18.04's packaged build of liblxi. There's already workarounds in the code (https://github.com/azonenberg/scopehal/issues/131).

Glad your problem is solved. Leaving this issue open until we figure out a more final path forward. It's likely we will document liblxi 1.13 as the new minimum required version and add a note to the README saying that the packaged version on Ubuntu 18.04 is known to not work.

**Comment by markrages** [comment]
Looks like liblxi v1.8 predates https://github.com/lxi-tools/liblxi/commit/4c71f5c41f80d87f2501482ee7e96f086007cb70, which is the `extern "C"` wrapper for the header file.

So version 1.8 and earlier will not link properly with C++.

**Comment by markrages** [comment]
For completeness:

I wrapped the `#include <lxi.h>` in `scopehal.h` with `extern "C" { }` and it compiled and linked against the system liblxi.

**Comment by azonenberg** [comment]
Can you make a clean pull of the latest HEAD using the system liblxi and confirm it builds properly?

**Comment by markrages** [comment]
Yes, it builds and links without errors with system liblxi.
